#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Ongawa.Resource", IsApplication=true)]

namespace Ongawa
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int ongawa_color = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int candado = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cemento = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ceramica = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ceramica1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int gota = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int hormigon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ladrillo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int madera = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int mosca = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ojo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int olor = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ongawa = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ongawa_activated_background_holo_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ongawa_btn_check_holo_light = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ongawa_btn_check_off_disabled_focused_holo_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ongawa_btn_check_off_disabled_holo_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ongawa_btn_check_off_focused_holo_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ongawa_btn_check_off_holo_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ongawa_btn_check_off_pressed_holo_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ongawa_btn_check_on_disabled_focused_holo_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ongawa_btn_check_on_disabled_holo_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ongawa_btn_check_on_focused_holo_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ongawa_btn_check_on_holo_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ongawa_btn_check_on_pressed_holo_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ongawa_btn_default_disabled_focused_holo_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ongawa_btn_default_disabled_holo_light = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ongawa_btn_default_focused_holo_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ongawa_btn_default_holo_light = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ongawa_btn_default_normal_holo_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ongawa_btn_default_pressed_holo_light = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ongawa_btn_toggle_holo_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ongawa_btn_toggle_off_disabled_focused_holo_light = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ongawa_btn_toggle_off_disabled_holo_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ongawa_btn_toggle_off_focused_holo_light = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ongawa_btn_toggle_off_normal_holo_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ongawa_btn_toggle_off_pressed_holo_light = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ongawa_btn_toggle_on_disabled_focused_holo_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ongawa_btn_toggle_on_disabled_holo_light = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ongawa_btn_toggle_on_focused_holo_light = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ongawa_btn_toggle_on_normal_holo_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ongawa_btn_toggle_on_pressed_holo_light = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ongawa_fastscroll_thumb_default_holo = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ongawa_fastscroll_thumb_holo = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ongawa_fastscroll_thumb_pressed_holo = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ongawa_item_background_holo_light = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ongawa_list_activated_holo = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ongawa_list_focused_holo = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ongawa_list_longpressed_holo = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ongawa_list_pressed_holo_light = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ongawa_list_selector_background_transition_holo_light = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ongawa_list_selector_disabled_holo_light = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ongawa_list_selector_holo_light = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int piedra = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ventilacion = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int water = 2130837559;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000c
			public const int LocStatus = 2131165196;
			
			// aapt resource value: 0x7f070009
			public const int address = 2131165193;
			
			// aapt resource value: 0x7f070026
			public const int agu = 2131165222;
			
			// aapt resource value: 0x7f070008
			public const int botGetLoc = 2131165192;
			
			// aapt resource value: 0x7f070034
			public const int button1 = 2131165236;
			
			// aapt resource value: 0x7f070033
			public const int button2 = 2131165235;
			
			// aapt resource value: 0x7f070003
			public const int cantBox = 2131165187;
			
			// aapt resource value: 0x7f07004d
			public const int cierre_candado = 2131165261;
			
			// aapt resource value: 0x7f070049
			public const int cierre_cemento = 2131165257;
			
			// aapt resource value: 0x7f07004a
			public const int cierre_ladrillo = 2131165258;
			
			// aapt resource value: 0x7f07004c
			public const int cierre_madera = 2131165260;
			
			// aapt resource value: 0x7f070000
			public const int contenedor = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int fechaBox = 2131165186;
			
			// aapt resource value: 0x7f070012
			public const int histButt = 2131165202;
			
			// aapt resource value: 0x7f07001e
			public const int imageCierre = 2131165214;
			
			// aapt resource value: 0x7f07001c
			public const int imageLosa = 2131165212;
			
			// aapt resource value: 0x7f070013
			public const int imageView1 = 2131165203;
			
			// aapt resource value: 0x7f07003d
			public const int imageView2 = 2131165245;
			
			// aapt resource value: 0x7f070021
			public const int imageView3 = 2131165217;
			
			// aapt resource value: 0x7f070025
			public const int imageView4 = 2131165221;
			
			// aapt resource value: 0x7f070029
			public const int imageView5 = 2131165225;
			
			// aapt resource value: 0x7f07002d
			public const int imageView6 = 2131165229;
			
			// aapt resource value: 0x7f070006
			public const int label1 = 2131165190;
			
			// aapt resource value: 0x7f07000e
			public const int label2 = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int label4 = 2131165201;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout1 = 2131165191;
			
			// aapt resource value: 0x7f070032
			public const int linearLayout10 = 2131165234;
			
			// aapt resource value: 0x7f070048
			public const int linearLayout11 = 2131165256;
			
			// aapt resource value: 0x7f07004b
			public const int linearLayout12 = 2131165259;
			
			// aapt resource value: 0x7f07000a
			public const int linearLayout2 = 2131165194;
			
			// aapt resource value: 0x7f07001f
			public const int linearLayout3 = 2131165215;
			
			// aapt resource value: 0x7f070023
			public const int linearLayout4 = 2131165219;
			
			// aapt resource value: 0x7f070027
			public const int linearLayout5 = 2131165223;
			
			// aapt resource value: 0x7f07002b
			public const int linearLayout6 = 2131165227;
			
			// aapt resource value: 0x7f07002f
			public const int linearLayout7 = 2131165231;
			
			// aapt resource value: 0x7f070047
			public const int linearLayout8 = 2131165255;
			
			// aapt resource value: 0x7f070044
			public const int linearLayout9 = 2131165252;
			
			// aapt resource value: 0x7f070004
			public const int listHist = 2131165188;
			
			// aapt resource value: 0x7f070018
			public const int locationtext = 2131165208;
			
			// aapt resource value: 0x7f070016
			public const int logButt = 2131165206;
			
			// aapt resource value: 0x7f070005
			public const int logOutButt = 2131165189;
			
			// aapt resource value: 0x7f07003a
			public const int losa_ceramica = 2131165242;
			
			// aapt resource value: 0x7f070039
			public const int losa_hormigon = 2131165241;
			
			// aapt resource value: 0x7f070037
			public const int losa_madera = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int losa_piedra = 2131165240;
			
			// aapt resource value: 0x7f07002a
			public const int mos = 2131165226;
			
			// aapt resource value: 0x7f070010
			public const int newButt = 2131165200;
			
			// aapt resource value: 0x7f07002e
			public const int olo = 2131165230;
			
			// aapt resource value: 0x7f070015
			public const int passBox = 2131165205;
			
			// aapt resource value: 0x7f070031
			public const int pri = 2131165233;
			
			// aapt resource value: 0x7f07000d
			public const int progBar = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int refFam = 2131165199;
			
			// aapt resource value: 0x7f07001a
			public const int refText = 2131165210;
			
			// aapt resource value: 0x7f070035
			public const int sanlab1 = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int sanlabel2 = 2131165238;
			
			// aapt resource value: 0x7f07003b
			public const int sanlabel3 = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public const int sanlabel4 = 2131165244;
			
			// aapt resource value: 0x7f070040
			public const int sanlabel5 = 2131165248;
			
			// aapt resource value: 0x7f070041
			public const int sanlabel6 = 2131165249;
			
			// aapt resource value: 0x7f070045
			public const int sanlabel8 = 2131165253;
			
			// aapt resource value: 0x7f070001
			public const int text1 = 2131165185;
			
			// aapt resource value: 0x7f070017
			public const int textView1 = 2131165207;
			
			// aapt resource value: 0x7f070024
			public const int textView10 = 2131165220;
			
			// aapt resource value: 0x7f070028
			public const int textView12 = 2131165224;
			
			// aapt resource value: 0x7f070030
			public const int textView13 = 2131165232;
			
			// aapt resource value: 0x7f07002c
			public const int textView14 = 2131165228;
			
			// aapt resource value: 0x7f07000b
			public const int textView2 = 2131165195;
			
			// aapt resource value: 0x7f070019
			public const int textView4 = 2131165209;
			
			// aapt resource value: 0x7f07001b
			public const int textView6 = 2131165211;
			
			// aapt resource value: 0x7f07001d
			public const int textView7 = 2131165213;
			
			// aapt resource value: 0x7f070020
			public const int textView8 = 2131165216;
			
			// aapt resource value: 0x7f07003e
			public const int toggleAgua = 2131165246;
			
			// aapt resource value: 0x7f070042
			public const int toggleMosc = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int toggleOlor = 2131165251;
			
			// aapt resource value: 0x7f070046
			public const int togglePriv = 2131165254;
			
			// aapt resource value: 0x7f07003f
			public const int toggleVent = 2131165247;
			
			// aapt resource value: 0x7f070014
			public const int usrBox = 2131165204;
			
			// aapt resource value: 0x7f070022
			public const int vent = 2131165218;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int filaListados = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Historico = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Inicio = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Resumen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Sanitario = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f05001d
			public const int aceptar = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int atras = 2131034140;
			
			// aapt resource value: 0x7f05000d
			public const int awaitLoc = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int errorEmptyForm = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int errorLoc = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int errorWrongUser = 2131034128;
			
			// aapt resource value: 0x7f050001
			public const int getLoc = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int gettingLoc = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int histButt = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int label1 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int label2 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int label3 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int label4 = 2131034124;
			
			// aapt resource value: 0x7f050005
			public const int loginBot = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int loginOut = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int newButt = 2131034119;
			
			// aapt resource value: 0x7f05001a
			public const int no = 2131034138;
			
			// aapt resource value: 0x7f050004
			public const int passHint = 2131034116;
			
			// aapt resource value: 0x7f05001e
			public const int reslabel1 = 2131034142;
			
			// aapt resource value: 0x7f050027
			public const int reslabel10 = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int reslabel11 = 2131034152;
			
			// aapt resource value: 0x7f05001f
			public const int reslabel2 = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int reslabel3 = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int reslabel4 = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int reslabel5 = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int reslabel6 = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int reslabel7 = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int reslabel8 = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int reslabel9 = 2131034150;
			
			// aapt resource value: 0x7f050011
			public const int sanlabel1 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int sanlabel2 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int sanlabel3 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int sanlabel4 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int sanlabel5 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int sanlabel6 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int sanlabel7 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int sanlabel8 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int si = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int siguiente = 2131034139;
			
			// aapt resource value: 0x7f050003
			public const int userHint = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int ButtonOngawa = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int CheckBoxOngawa = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int ImageButtonOngawa = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int ListViewOngawa = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int ListViewOngawa_White = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int Ongawa = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int SpinnerItemOngawa = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int ToggleOngawa = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int _Ongawa = 2131099656;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
